import assert from 'node:assert/strict';
import test from 'node:test';
import {mkdtemp,rm,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {runInNewContext} from 'node:vm';
import {TerminalManager} from '../src/main/services/TerminalManager.ts';
import {TerminalSessionStore} from '../src/main/services/TerminalSessionStore.ts';
import {WorkspaceArchive} from '../src/main/services/WorkspaceArchive.ts';
import {OrchestrationTaskBoard} from '../src/main/services/OrchestrationTaskBoard.ts';
import {registerBacklogIpc} from '../src/main/ipc/registerBacklogIpc.ts';
import {BACKLOG_IPC} from '../src/shared/backlog.ts';
import {availableRegistry,fakeSpawner} from './helpers/terminal.mjs';
for(const mode of ['off','reopen'])test(`workspace export/preset uses live card bounds and matching task groups with restoration ${mode}`,async t=>{
 const dir=await mkdtemp(join(tmpdir(),'ctty-live-export-'));const calls=[];
 const manager=new TerminalManager(()=>{},availableRegistry(),undefined,undefined,true,fakeSpawner(calls));
 const store=new TerminalSessionStore(dir);await store.load();manager.configureSessionPersistence(store,mode);
 t.after(async()=>{await manager.shutdown();await rm(dir,{recursive:true,force:true});});
 const root=manager.create({provider:'codex',profile:'normal',role:'orchestrator',cwd:dir,position:{x:0,y:0}});
 const child=manager.create({provider:'codex',profile:'normal',parentSessionId:root.id,cwd:dir,position:{x:20,y:30}});
 const reviewer=manager.create({provider:'codex',profile:'normal',cwd:dir,position:{x:1,y:1}});
 // Temporary reviewer state is host-owned and must be excluded even while visible in the manager.
 manager.sessions.get(reviewer.id).reviewWorkspace={cleanup(){}};
 manager.sessions.get(root.id).threadId='11111111-1111-4111-8111-111111111111';
 manager.sessions.get(root.id).extras.options={'example.plugin':{account:'private-account-marker'}};
 calls[0].process.emitData('private-buffer-marker');
 const bounds={position:{x:880,y:990},size:{width:800,height:650}};manager.setBounds(root.id,bounds);
 if(mode==='off')assert.deepEqual(store.get(),[]);
 else assert.notDeepEqual(store.get().find(row=>row.id===root.id).position,bounds.position,'persistence still has pre-drag bounds');
 const main=await readFile(new URL('../src/main/index.ts',import.meta.url),'utf8');
 const descriptorExpression=main.match(/descriptors: (\(\) => [^,]+),/)[1];
 const descriptors=runInNewContext(descriptorExpression,{managedTerminals:manager,terminalSessionStore:store});
 const archive=new WorkspaceArchive(dir,{descriptors,create:r=>manager.create(r),setBounds:(...a)=>manager.setBounds(...a),available:()=>true,redact:x=>x});
 const board=new OrchestrationTaskBoard(join(dir,'boards'));await board.addTask(dir,root.id,root.id,{title:'Exported task'});await board.addTask(dir,reviewer.id,reviewer.id,{title:'Private reviewer task'});
 const handlers=new Map(),webContents={mainFrame:{}};registerBacklogIpc({handle:(k,v)=>handlers.set(k,v)},{terminals:manager,workspace:archive,board,taskRoot:id=>manager.taskScopeFor(id),getMainWindow:()=>({webContents})});
 const event={sender:webContents,senderFrame:webContents.mainFrame};const text=await handlers.get(BACKLOG_IPC.exportWorkspace)(event);const value=JSON.parse(text);
 assert.deepEqual(value.sessions.map(x=>x.id),[root.id,child.id]);assert.deepEqual(value.sessions[0].position,bounds.position);assert.deepEqual(value.sessions[0].size,bounds.size);
 assert.equal(value.sessions[0].threadId,'11111111-1111-4111-8111-111111111111');assert.doesNotMatch(text,/private-account-marker|private-buffer-marker|Private reviewer task/);
 assert.equal(value.tasks.length,1);assert.equal(value.tasks[0].rootSessionId,root.id);assert.equal(value.tasks[0].tasks[0].title,'Exported task');
 for(const group of value.tasks)assert.ok(value.sessions.some(row=>row.id===group.rootSessionId));
 await archive.savePreset({id:'live',name:'Live canvas',snapshot:text});const preset=JSON.parse((await archive.presets())[0].snapshot);
 assert.deepEqual(preset.sessions.map(x=>x.id),[root.id,child.id]);assert.equal(preset.sessions[0].threadId,undefined);assert.deepEqual(preset.sessions[0].position,bounds.position);assert.equal(preset.tasks[0].rootSessionId,root.id);
 assert.equal((await archive.preview(text)).count,2);
});
