import type { LocaleId } from "../../../../shared/contracts";
const text = {
  inspector: ["События сессии", "Session activity"],
  timelineText: ["Поиск по событиям", "Search events"],
  timelineType: ["Тип события", "Event type"],
  timelineAgent: ["Карточка", "Card"],
  timelineSearch: ["Искать", "Search"],
  timelineAll: ["Все", "All"],
  inspectorTabs: ["Разделы событий сессии", "Session activity sections"],
  tabTimeline: ["Хронология", "Timeline"],
  tabUsage: ["Расход", "Usage"],
  tabReport: ["Отчёт", "Report"],
  tabCheckpoints: ["Контрольные точки", "Checkpoints"],
  restoreConfirm: ["Восстановить эту контрольную точку? Текущие изменения могут быть потеряны.", "Restore this checkpoint? Current changes may be lost."],
  restoreFailed: ["Не удалось восстановить контрольную точку.", "Could not restore the checkpoint."],
  noTimeline: ["Событий пока нет.", "No timeline events yet."],
  loadMore: ["Загрузить ещё", "Load more"],
  inputTokens: ["Входные токены", "Input tokens"],
  outputTokens: ["Выходные токены", "Output tokens"],
  cost: ["Стоимость", "Cost"],
  usageSource: ["Источник", "Source"],
  usageUnknown: ["Нет данных о расходе.", "Usage data is unavailable."],
  conversationTokens: ["Всего токенов беседы", "Conversation total tokens"],
  exportReport: ["Скачать Markdown", "Download Markdown"],
  noReport: ["Отчёт пока пуст.", "No report available yet."],
  checkpoint: ["Контрольная точка", "Checkpoint"],
  noCheckpoints: ["Контрольных точек нет.", "No checkpoints available."],
  preview: ["Предпросмотр", "Preview"],
  restoreCheckpoint: ["Восстановить точку", "Restore checkpoint"],
  back: ["Назад к списку", "Back to list"],
  taskSummary: ["Сводка задачи", "Task summary"],
  working: ["работают", "working"],
  waiting: ["ждут", "waiting"],
  done: ["готовы", "done"],
  failed: ["ошибки", "failed"],
  elapsed: ["Прошло с начала задачи", "Elapsed since task start"],
  gatherTask: ["Собрать задачу", "Gather task"],
  taskStateWaitingResponse: ["Ожидает ответа", "Waiting for response"],
  taskStateWorking: ["В работе", "Working"],
  taskStateWaiting: ["Ожидает подтверждения", "Waiting for approval"],
  taskStateDone: ["Готово", "Done"],
  taskStateFailed: ["Ошибка", "Failed"],
  tabTasks: ["Задачи", "Tasks"],
  tabBudget: ["Бюджет", "Budget"],
  taskBoard: ["Общая доска задачи", "Shared task board"],
  taskTitle: ["Название задачи", "Task title"],
  taskDescription: ["Описание", "Description"],
  taskDependencies: ["Зависимости — ID через запятую", "Dependencies — comma-separated IDs"],
  taskOwner: ["Исполнитель", "Owner"],
  unassigned: ["Не назначен", "Unassigned"],
  addTask: ["Добавить задачу", "Add task"],
  noTasks: ["В этой задаче нет подзадач.", "No subtasks in this task."],
  closeTask: ["Закрыть", "Close"],
  taskOpen: ["Открыта", "Open"],
  taskClaimed: ["В работе", "Claimed"],
  taskDone: ["Готова", "Done"],
  taskClosed: ["Закрыта", "Closed"],
  budgetLimits: ["Лимиты задачи и всего дерева", "Task and tree limits"],
  budgetTokens: ["Токены", "Tokens"],
  budgetCost: ["Стоимость, USD", "Cost, USD"],
  budgetMinutes: ["Время, минуты", "Time, minutes"],
  budgetUsage: ["Использовано", "Used"],
  budgetRemaining: ["Остаток", "Remaining"],
  budgetDataNone: ["Нет данных от CLI", "CLI did not provide this data"],
  budgetDataPartial: ["Неизвестно: часть затрат", "Unknown: some costs are unavailable"],
  budgetCostPartialPause: ["Бюджет стоимости приостановил задачу: затраты известны не по всем участникам.", "The cost budget paused this task because cost is unknown for some members."],
  budgetPaused: ["Лимит достигнут: подагенты приостановлены.", "Limit reached: subagents are paused."],
  budgetWarning: ["Достигнут порог предупреждения.", "The warning threshold has been reached."],
  budgetSet: ["Сохранить лимиты", "Save limits"],
  budgetRaise: ["Поднять лимиты на 25%", "Raise limits by 25%"],
  budgetClear: ["Снять бюджет", "Clear budget"],
  budgetNoLimits: ["Лимиты не заданы.", "No limits set."],
  budgetReason: ["Причина паузы", "Pause reason"],
  tabNotifications: ["Уведомления", "Notifications"],
  notificationChannels: ["Каналы", "Channels"],
  notificationDesktop: ["Рабочий стол", "Desktop"],
  notificationGlasses: ["Очки", "Glasses"],
  notificationDnd: ["Не беспокоить", "Do not disturb"],
  notificationDndOff: ["Выключено", "Off"],
  notificationDndHour: ["На 1 час", "For 1 hour"],
  notificationDndUntilClear: ["Пока не выключу", "Until cleared"],
  notificationImportantOnly: ["Только важные события", "Important events only"],
  notificationThisCard: ["Только эта карточка", "This card only"],
  saveTaskFlow: ["Сохранить подзадачи как workflow…", "Save subtasks as workflow…"],
  flowName: ["Название workflow", "Workflow name"],
  flowSaved: ["Файл workflow сохранён", "Workflow file saved"],
  reviewRequested: ["Требуется проверка", "Review requested"],
} as const;
export type BacklogTextKey = keyof typeof text;
export function backlogText(locale: LocaleId, key: BacklogTextKey): string { return text[key][locale === "ru" ? 0 : 1]; }
