import type { LocaleId } from "../../../../shared/contracts";
const text = {
  tabCheckpoints: ["Точки отката", "Rollback points"],
  restoreConfirm: ["Восстановить эту контрольную точку? Текущие изменения могут быть потеряны.", "Restore this checkpoint? Current changes may be lost."],
  restoreFailed: ["Не удалось восстановить контрольную точку.", "Could not restore the checkpoint."],
  checkpoint: ["Контрольная точка", "Checkpoint"], noCheckpoints: ["Контрольных точек нет.", "No checkpoints available."],
  preview: ["Предпросмотр", "Preview"], restoreCheckpoint: ["Восстановить точку", "Restore checkpoint"], back: ["Назад к списку", "Back to list"],
  taskStateFailed: ["Ошибка", "Failed"],
  taskStateDone: ["Готово", "Done"],
  taskStateWaitingResponse: ["Ожидает ответа", "Waiting for response"],
  taskStateWaiting: ["Ожидает подтверждения", "Waiting for approval"],
  taskStateWorking: ["В работе", "Working"],
  addTask: ["Добавить задачу", "Add task"],
  budgetClear: ["Снять бюджет", "Clear budget"],
  budgetCost: ["Стоимость, USD", "Cost, USD"],
  budgetCostPartialPause: ["Бюджет стоимости приостановил задачу: затраты известны не по всем участникам.", "The cost budget paused this task because cost is unknown for some members."],
  budgetDataNone: ["Нет данных от CLI", "CLI did not provide this data"],
  budgetDataPartial: ["Неизвестно: часть затрат", "Unknown: some costs are unavailable"],
  budgetLimits: ["Лимиты задачи и всего дерева", "Task and tree limits"],
  budgetMinutes: ["Время, минуты", "Time, minutes"],
  budgetNoLimits: ["Лимиты не заданы.", "No limits set."],
  budgetPaused: ["Лимит достигнут: подагенты приостановлены.", "Limit reached: subagents are paused."],
  budgetRaise: ["Поднять лимиты на 25%", "Raise limits by 25%"],
  budgetReason: ["Причина паузы", "Pause reason"],
  budgetRemaining: ["Остаток", "Remaining"],
  budgetSet: ["Сохранить лимиты", "Save limits"],
  budgetTokens: ["Токены", "Tokens"],
  budgetUsage: ["Использовано", "Used"],
  budgetWarning: ["Достигнут порог предупреждения.", "The warning threshold has been reached."],
  closeTask: ["Закрыть", "Close"],
  done: ["готовы", "done"],
  elapsed: ["Прошло с начала задачи", "Elapsed since task start"],
  failed: ["ошибки", "failed"],
  flowName: ["Название workflow", "Workflow name"],
  flowSaved: ["Файл workflow сохранён", "Workflow file saved"],
  gatherTask: ["Собрать задачу", "Gather task"],
  inspector: ["Задачи и точки отката", "Tasks and rollback points"],
  inspectorTabs: ["Разделы задачи", "Task sections"],
  noTasks: ["В этой задаче нет подзадач.", "No subtasks in this task."],
  reviewRequested: ["Требуется проверка", "Review requested"],
  saveTaskFlow: ["Сохранить подзадачи как workflow…", "Save subtasks as workflow…"],
  tabBudget: ["Бюджет", "Budget"],
  tabTasks: ["Задачи", "Tasks"],
  taskBoard: ["Общая доска задачи", "Shared task board"],
  taskClaimed: ["В работе", "Claimed"],
  taskClosed: ["Закрыта", "Closed"],
  taskDependencies: ["Зависимости — ID через запятую", "Dependencies — comma-separated IDs"],
  taskDescription: ["Описание", "Description"],
  taskDone: ["Готова", "Done"],
  taskOpen: ["Открыта", "Open"],
  taskOwner: ["Исполнитель", "Owner"],
  taskSummary: ["Сводка задачи", "Task summary"],
  taskTitle: ["Название задачи", "Task title"],
  unassigned: ["Не назначен", "Unassigned"],
  waiting: ["ждут", "waiting"],
  working: ["работают", "working"],
} as const;
export type BacklogTextKey = keyof typeof text;
export function backlogText(locale: LocaleId, key: BacklogTextKey): string { return text[key][locale === "ru" ? 0 : 1]; }
