import { useEffect, useState } from 'react';
import type { AppSettings, ContainerProfile, ProviderId, RemoteWorkspaceReview, RetainedContainer } from '../../../../shared/contracts';
import { assertContainerProfile } from '../../../../shared/containerProfiles';
import { ContainerInventorySettings } from './ContainerInventorySettings';

export function ContainerProfilesSettings({ settings, active = true, recordId, selectionRequest, onPersist }: { settings: AppSettings; active?: boolean; recordId?: string; selectionRequest?: unknown; onPersist(patch: Partial<AppSettings>): Promise<void> }): React.JSX.Element {
  const ru = settings.locale === 'ru';
  const text = (en: string, russian: string): string => ru ? russian : en;
  const [draft, setDraft] = useState<ContainerProfile | null>(null);
  useEffect(() => { if (recordId) { const profile = settings.containerProfiles.find(item => item.id === recordId); if (profile) setDraft(current => current?.id === recordId ? current : structuredClone(profile)); } }, [recordId, selectionRequest]);
  const [provider, setProvider] = useState<ProviderId>('opencode');
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState('');
  const [retained, setRetained] = useState<RetainedContainer[] | null>(null);
  const [review, setReview] = useState<RemoteWorkspaceReview | null>(null);
  const run = async (operation: () => Promise<void>): Promise<void> => { setBusy(true); setMessage(''); try { await operation(); } catch (error) { setMessage(error instanceof Error ? error.message : String(error)); } finally { setBusy(false); } };
  const set = (patch: Partial<ContainerProfile>): void => setDraft(value => value && ({ ...value, ...patch }));
  return <section aria-label={text('Container profiles', 'Профили контейнеров')} className="container-profiles">
    <ContainerInventorySettings settings={settings} active={active} />
    <div className="agent-settings-heading"><h3>{text('Container profiles', 'Профили контейнеров')}</h3></div>
    <p className="agent-settings-hint">{text('Existing Docker / Podman only. Images and Python must already be installed; engines and virtual machines are never started automatically. Full committed workspace is mounted; source classification is preserved.', 'Только уже доступные Docker / Podman. Образ и Python должны быть подготовлены заранее; движки и виртуальные машины не запускаются автоматически. Монтируется весь checkout из Git; класс данных исходного проекта сохраняется.')}</p>
    {(settings.containerProfiles ?? []).map(p => <div className="container-profiles__card" key={p.id}>
      <strong>{p.label}</strong> · {p.runtime} · {p.hostId === 'local' ? text('This computer', 'Этот компьютер') : settings.remoteHosts.find(h => h.id === p.hostId)?.label ?? text('Missing server', 'Сервер не найден')} · {p.network}
      <button className="agent-settings-button" type="button" disabled={busy} onClick={() => { setDraft(structuredClone(p)); setProvider(Object.keys(p.commands)[0] as ProviderId); }}>{text('Edit', 'Изменить')}</button>
      <button className="agent-settings-button" type="button" disabled={busy} onClick={() => void run(async () => { const status = await window.canvasTTY.containers.probe(p.id); setMessage(status.available ? `${text('Engine and image available', 'Движок и образ доступны')}: ${status.imageId}. ${text('CLI and effective limits are verified at launch.', 'CLI и фактические лимиты проверяются при запуске.')}` : status.reason ?? 'Unavailable'); })}>{text('Check engine and image', 'Проверить движок и образ')}</button>
      <button className="agent-settings-button" type="button" disabled={busy} onClick={() => void run(async () => { if ((await window.canvasTTY.containers.list()).some(item => item.profileId === p.id && item.state !== 'workspace-retained')) throw new Error(text('Clean the owned containers before removing this profile.', 'Сначала остановите и удалите контейнеры этого профиля.')); await onPersist({ containerProfiles: settings.containerProfiles.filter(item => item.id !== p.id) }); })}>{text('Remove profile', 'Удалить профиль')}</button>
      {p.commands.terminal && <button className="agent-settings-button agent-settings-button--primary" type="button" disabled={busy} onClick={() => void run(async () => {
        const cwd = await window.canvasTTY.dialog.pickDirectory(settings.lastDirectory); if (!cwd) return;
        await window.canvasTTY.terminal.create({ provider: 'terminal', profile: 'normal', cwd, isolation: { mode: 'container', profileId: p.id }, ...(p.hostId !== 'local' ? { hostId: p.hostId } : {}), position: { x: 40, y: 40 } });
        setMessage(text('Shell preparation started. Its window shows the launch result.', 'Подготовка shell начата. Результат запуска появится в окне терминала.'));
      })}>{text('Launch shell in container…', 'Открыть shell в контейнере…')}</button>}
    </div>)}
    <button className="agent-settings-button" type="button" disabled={busy} onClick={() => { setProvider('opencode'); setDraft({ id: crypto.randomUUID(), label: 'Sandbox', hostId: 'local', runtime: 'docker', executable: '/usr/bin/docker', endpoint: { kind: 'unix', socket: '/var/run/docker.sock' }, image: '', python: '/usr/bin/python3', commands: { opencode: '/usr/local/bin/opencode' }, network: 'none', cpus: 2, memoryMb: 2048, pids: 256, user: '1000:1000' }); }}>{text('Add container profile', 'Добавить профиль контейнера')}</button>
    {draft && <fieldset className="container-profiles__editor agent-settings-grid" disabled={busy}>
      <legend>{text('Image and execution host', 'Образ и сервер исполнения')}</legend>
      <label className="agent-settings-field"><span>{text('Name', 'Название')}</span><input value={draft.label} maxLength={100} onChange={e => set({ label: e.target.value })} /></label>
      <label className="agent-settings-field"><span>{text('Host', 'Сервер')}</span><select value={draft.hostId} onChange={e => set({ hostId: e.target.value, ...(e.target.value !== 'local' ? { hostPython: '/usr/bin/python3' } : {}) })}><option value="local">Local</option>{settings.remoteHosts.map(host => <option key={host.id} value={host.id}>{host.label}</option>)}</select></label>
      <label className="agent-settings-field"><span>{text('Engine', 'Движок')}</span><select value={draft.runtime} onChange={e => set({ runtime: e.target.value as 'docker' | 'podman', ...(e.target.value === 'docker' && draft.endpoint.kind === 'native' ? { endpoint: { kind: 'unix' as const, socket: '/var/run/docker.sock' } } : {}), user: e.target.value === 'podman' ? 'keep-id' : '1000:1000' })}><option value="docker">Docker</option><option value="podman">Podman</option></select></label>
      <label className="agent-settings-field"><span>{text('Engine executable on host', 'Путь к движку на сервере')}</span><input value={draft.executable} onChange={e => set({ executable: e.target.value })} /></label>
      <label className="agent-settings-field"><span>{text('Engine endpoint', 'Endpoint движка')}</span><select value={draft.endpoint.kind} onChange={e => set({ endpoint: e.target.value === 'native' ? { kind: 'native' } : { kind: 'unix', socket: '/var/run/docker.sock' } })}><option value="unix">UNIX socket</option>{draft.runtime === 'podman' && <option value="native">Native Podman Linux</option>}</select></label>
      {draft.endpoint.kind === 'unix' && <label className="agent-settings-field"><span>Socket</span><input value={draft.endpoint.socket} onChange={e => set({ endpoint: { kind: 'unix', socket: e.target.value } })} /></label>}
      <label className="agent-settings-field"><span>{text('Existing image', 'Локальный образ')}</span><input value={draft.image} onChange={e => set({ image: e.target.value })} /></label>
      <label className="agent-settings-field"><span>{text('Python inside image', 'Python внутри образа')}</span><input value={draft.python} onChange={e => set({ python: e.target.value })} /></label>
      {draft.hostId !== 'local' && <label className="agent-settings-field"><span>{text('Python on remote host', 'Python на удалённом сервере')}</span><input value={draft.hostPython ?? ''} onChange={e => set({ hostPython: e.target.value })} /></label>}
      <label className="agent-settings-field"><span>{text('Image command', 'Команда в образе')}</span><select value={provider} onChange={e => { setProvider(e.target.value as ProviderId); set({ commands: { ...draft.commands, [e.target.value]: draft.commands[e.target.value as ProviderId] ?? (e.target.value === 'terminal' ? '/bin/sh' : `/usr/local/bin/${e.target.value}`) } }); }}>{['terminal', 'opencode', 'minimax', 'omp'].map(id => <option key={id} value={id}>{id}</option>)}</select></label><label className="agent-settings-field"><span>{text('Executable inside image', 'Исполняемый файл внутри образа')}</span><input value={draft.commands[provider] ?? ''} onChange={e => set({ commands: { ...draft.commands, [provider]: e.target.value } })} /></label>
      <label className="agent-settings-field"><span>{text('User mapping', 'UID / GID')}</span><input value={draft.user} onChange={e => set({ user: e.target.value })} /></label>
      <p className="agent-settings-hint agent-settings-field--wide">{text('Rootless Docker: 0:0. Podman: keep-id. Rootful Docker: workspace owner UID:GID. No automatic ownership changes.', 'Rootless Docker: 0:0. Podman: keep-id. Rootful Docker: UID:GID владельца workspace. Права файлов автоматически не меняются.')}</p>
      <label className="agent-settings-field"><span>CPU</span><input type="number" min="0.1" max="32" step="0.1" value={draft.cpus} onChange={e => set({ cpus: Number(e.target.value) })} /></label>
      <label className="agent-settings-field"><span>RAM MiB</span><input type="number" min="128" max="65536" value={draft.memoryMb} onChange={e => set({ memoryMb: Number(e.target.value) })} /></label>
      <label className="agent-settings-field"><span>PID</span><input type="number" min="16" max="4096" value={draft.pids} onChange={e => set({ pids: Number(e.target.value) })} /></label>
      <label className="agent-settings-field"><span>{text('Network', 'Сеть')}</span><select value={draft.network} onChange={e => set({ network: e.target.value as 'none' | 'bridge' })}><option value="none">None</option><option value="bridge">Bridge — outbound internet</option></select></label>
      <p className="agent-settings-hint agent-settings-field--wide">{text('API accounts use private in-container configuration. Remote accounts use a key provisioned on their fixed server. Native OAuth homes are unavailable in containers. Linked Git metadata stays outside the mount.', 'API-аккаунты используют приватную конфигурацию внутри контейнера. Для удалённого аккаунта ключ хранится на закреплённом сервере. Native OAuth в контейнерах недоступен. Связанные метаданные Git остаются вне mount.')}</p>
      <button className="agent-settings-button agent-settings-button--primary" type="button" onClick={() => void run(async () => { assertContainerProfile(draft); await onPersist({ containerProfiles: [...settings.containerProfiles.filter(p => p.id !== draft.id), draft] }); setDraft(null); })}>{text('Save profile', 'Сохранить профиль')}</button>
      <button className="agent-settings-button" type="button" onClick={() => setDraft(null)}>{text('Cancel', 'Отмена')}</button>
    </fieldset>}
    <button className="agent-settings-button" type="button" disabled={busy} onClick={() => void run(async () => setRetained(await window.canvasTTY.containers.list()))}>{text('Show retained containers', 'Показать сохранённые контейнеры')}</button>
    {retained?.map(item => <div className="container-profiles__card" key={item.id}>
      <strong>{settings.remoteHosts.find(host => host.id === item.hostId)?.label ?? item.hostId}</strong><code>{item.hostWorkspace}</code>
      <p className="agent-settings-hint">{item.state === 'workspace-retained' ? text('Container stopped. Output remains on its server for review and patch export.', 'Контейнер остановлен. Результат сохранён на сервере: можно просмотреть изменения и экспортировать патч.') : item.reason ?? item.state}</p>
      {item.state !== 'workspace-retained' ? <button className="agent-settings-button" type="button" disabled={busy} onClick={() => void run(async () => { await window.canvasTTY.containers.cleanup(item.id); setRetained(await window.canvasTTY.containers.list()); })}>{text('Stop and remove owned container', 'Остановить и удалить свой контейнер')}</button>
        : item.hostId !== 'local' && <button className="agent-settings-button" type="button" disabled={busy} onClick={() => void run(async () => { setReview(null); setReview(await window.canvasTTY.containers.review(item.id)); })}>{text('Review changes', 'Просмотреть изменения')}</button>}
    </div>)}
    {review && <section className="retained-workspaces__review" aria-label={text('Remote output review', 'Изменения на сервере')}>
      <div className="agent-settings-heading"><strong>{text('Changes on server', 'Изменения на сервере')}: {settings.remoteHosts.find(host => host.id === review.hostId)?.label ?? review.hostId}</strong><button className="agent-settings-button" type="button" disabled={busy} onClick={() => setReview(null)}>{text('Close', 'Закрыть')}</button></div>
      <p className="agent-settings-hint">{text('Tracked changes from the launch commit. Untracked and ignored files are omitted. Git filters and text conversion are disabled.', 'Изменения отслеживаемых файлов с момента запуска. Новые неотслеживаемые и игнорируемые файлы не входят в патч. Фильтры Git и преобразование текста отключены.')}</p>
      <p className="agent-settings-hint">{text('Omitted files', 'Файлы вне патча')}: {text('untracked', 'неотслеживаемые')} — {review.untrackedFiles}; {text('ignored', 'игнорируемые')} — {review.ignoredFiles}.</p>
      {review.headCommit !== review.baseCommit && <p className="agent-settings-hint">{text('Includes commits made after launch.', 'Включены коммиты, созданные после запуска.')}</p>}
      <pre className="container-profiles__patch" tabIndex={0} aria-label={text('Git patch', 'Патч Git')}>{review.patch || text('No tracked changes. Check the omitted file counts above.', 'Изменений отслеживаемых файлов нет. Проверьте число файлов вне патча выше.')}</pre>
      <details className="retained-workspaces__help"><summary>{text('Review limits', 'Ограничения просмотра')}</summary><p className="agent-settings-hint">{text('Up to 20,000 entries, 16 MiB per file, 64 MiB total and a 512 KiB patch. Linked files and unsupported Git metadata prevent review. Output remains on the server.', 'До 20 000 записей, 16 МиБ на файл, 64 МиБ суммарно и 512 КиБ на патч. Ссылки и неподдерживаемые метаданные Git блокируют просмотр. Результат остаётся на сервере.')}</p></details>
      <button className="agent-settings-button agent-settings-button--primary" type="button" disabled={busy || !review.patch} onClick={() => void run(async () => {
        try { const saved = await window.canvasTTY.containers.exportPatch(review.generationId, review.reviewId); setMessage(saved ? text('Patch saved. Output remains on its server.', 'Патч сохранён. Результат остаётся на сервере.') : text('Export cancelled.', 'Экспорт отменён.')); }
        catch { setReview(null); throw new Error(text('Export failed. Review the remote output again before exporting.', 'Экспорт не выполнен. Просмотрите результат на сервере заново перед экспортом.')); }
      })}>{text('Save verified patch', 'Сохранить проверенный патч')}</button>
    </section>}
    {message && <p className="agent-settings-notice" role="status">{message}</p>}
  </section>;
}
