import { useEffect, useRef, useState } from 'react';
import { DECISION_CATEGORIES, DECISION_DIFFICULTIES, routeEconomics, type DecisionCategory, type DecisionDifficulty, type DecisionInput, type DecisionRecommendation } from '../../../../shared/decisions';
import { effortLabel } from '../../lib/effort';
import type { AgentProviderId, AppSettings } from '../../../../shared/contracts';
import type { SettingsLocation } from '../../../../shared/settingsLocation';
import type { LaunchDraft } from './launchDraft';
import { PROVIDERS } from '../../lib/providers';
import { ProviderIcon } from '../../components/ProviderIcon';
export function decisionLaunchInput(draft: LaunchDraft, settings: AppSettings, category: DecisionCategory, difficulty?: DecisionDifficulty): DecisionInput {
 if (draft.capsule || draft.containerRoute === 'auto' && draft.isolation === 'container') throw new Error(settings.locale === 'ru' ? 'Для рекомендации выберите прямой запуск, worktree или конкретный профиль контейнера.' : 'Choose direct, worktree or a fixed container profile for recommendations.');
 const account = settings.providerAccounts.find(a => a.id === draft.accountId);
 return { cwd: draft.cwd, profile: draft.profile, category, ...(difficulty ? { difficulty } : {}), transport: draft.transport, ...(draft.effort ? { effort: draft.effort } : {}),
  context: settings.contextProfilesEnabled && (draft.contextEnabled ?? true) ? { enabled: true, ...(draft.contextTaskId ? { taskId: draft.contextTaskId } : {}), ...(draft.contextCategories ? { categories: draft.contextCategories } : {}), ...(draft.currentContext?.length ? { current: draft.currentContext } : {}) } : { enabled: false },
  ...(draft.allowSubagents ? { allowSubagents: true } : {}), ...(draft.initialPrompt?.trim() ? { initialPrompt: draft.initialPrompt } : {}),
  ...(draft.accountId ? { accountId: draft.accountId, hostId: account?.hostId ?? 'local' } : {}), ...(draft.model.trim() ? { model: draft.model.trim() } : {}), ...(draft.dataClass ? { dataClass: draft.dataClass } : {}),
  isolation: draft.isolation === 'container' ? { mode: 'container', profileId: draft.containerProfileId } : draft.isolation === 'worktree' ? { mode: 'worktree', ref: draft.ref.trim() || 'HEAD' } : { mode: 'direct' } };
}
const reasons: Record<string, [string, string]> = { 'metadata-grant-required': ['Нет разрешения на отправку признаков', 'Metadata disclosure not allowed'], 'evaluation-budget': ['Достигнут лимит оценок', 'Evaluation budget reached'], 'credential-required': ['Не настроен отдельный ключ Jev', 'Separate Jev key missing'], 'credential-unavailable': ['Ключ Jev недоступен', 'Jev key unavailable'], 'low-confidence': ['Недостаточная уверенность Jev', 'Jev confidence below threshold'], 'evaluation-unavailable': ['Оценка Jev недоступна', 'Jev evaluation unavailable'] };
export function LaunchDecision({ draft, settings, active, disabled, onLaunch, onClose, onOpenSettings, onAcknowledge }: { draft: LaunchDraft; settings: AppSettings; active: boolean; disabled: boolean; onLaunch(id: string): Promise<void>; onClose(): void; onOpenSettings(location: SettingsLocation): void; onAcknowledge(provider: AgentProviderId): Promise<void> }): React.JSX.Element {
 const ru = settings.locale === 'ru', [category, setCategory] = useState<DecisionCategory>('general'), [difficulty, setDifficulty] = useState<DecisionDifficulty>('normal'), [result, setResult] = useState<DecisionRecommendation | null>(null), [applied, setApplied] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState('');
 const generation = useRef(0), resultRef = useRef<DecisionRecommendation | null>(null), current = useRef({ draft, settings, active }); current.current = { draft, settings, active };
 useEffect(() => { generation.current++; setResult(null); setApplied(false); setError(''); const old = resultRef.current; resultRef.current = null; if (old) void window.canvasTTY.decisions.cancel(old.id).catch(() => {}); }, [draft, settings, active, category, difficulty]);
 useEffect(() => () => { generation.current++; const old = resultRef.current; if (old) void window.canvasTTY.decisions.cancel(old.id).catch(() => {}); }, []);
 const recommend = async (): Promise<void> => {
  const token = ++generation.current; setBusy(true); setError(''); setResult(null); setApplied(false);
  try { const next = await window.canvasTTY.decisions.recommend(decisionLaunchInput(draft, settings, category, difficulty));
   if (generation.current !== token || current.current.draft !== draft || current.current.settings !== settings || !current.current.active) { void window.canvasTTY.decisions.cancel(next.id).catch(() => {}); return; }
   if (resultRef.current) void window.canvasTTY.decisions.cancel(resultRef.current.id).catch(() => {}); resultRef.current = next; setResult(next);
  } catch (e) { if (generation.current === token) setError(e instanceof Error ? e.message : String(e)); }
  finally { setBusy(false); }
 };
 const launch = async (): Promise<void> => { if (!result || !applied) return; setBusy(true); setError(''); try { await onLaunch(result.id); resultRef.current = null; onClose(); } catch (e) { setApplied(false); setError(e instanceof Error ? e.message : String(e)); } finally { setBusy(false); } };
 const acknowledged = !result || draft.profile !== 'yolo' || settings.acknowledgedDangerousProfiles.includes(result.selected.provider);
 return <details className="launch-decision"><summary>{ru ? 'Подобрать другого исполнителя' : 'Recommend an agent'}</summary>
  <p>{ru ? 'Проверяет настроенные связки. Выбранные аккаунт, модель, способ запуска и доступ сохраняются как ограничения. Рекомендация требует отдельного применения и запуска.' : 'Checks configured routes. Selected account, model, transport and access remain constraints. Review, apply and launch are separate steps.'}</p>
  {settings.decisions?.mode !== 'off' && settings.decisions ? <>
   <label>{ru ? 'Тип задачи' : 'Task category'}<select disabled={disabled || busy} value={category} onChange={e => setCategory(e.target.value as DecisionCategory)}>{DECISION_CATEGORIES.map(c => <option key={c} value={c}>{ru ? ({ general: 'Общая', code: 'Код', review: 'Проверка', research: 'Исследование', writing: 'Текст' })[c] : c}</option>)}</select></label>
   <label>{ru ? 'Сложность задачи' : 'Task difficulty'}<select disabled={disabled || busy} value={difficulty} onChange={e => setDifficulty(e.target.value as DecisionDifficulty)}>{DECISION_DIFFICULTIES.map(d => <option key={d} value={d}>{ru ? ({ simple: 'Простая — дешевле и быстрее', normal: 'Обычная', hard: 'Сложная — сильнее, но дороже' })[d] : ({ simple: 'Simple — cheaper and faster', normal: 'Normal', hard: 'Hard — stronger but costlier' })[d]}</option>)}</select></label>
   <button type="button" className="agent-settings-button" disabled={disabled || busy || !active} onClick={() => void recommend()}>{busy ? (ru ? 'Проверка…' : 'Checking…') : (ru ? 'Получить рекомендацию' : 'Get recommendation')}</button>
   {result && <div className="launch-decision__result" role="status"><ProviderIcon provider={result.selected.provider} /><strong>{PROVIDERS[result.selected.provider].label}</strong><p>{settings.providerAccounts.find(a => a.id === result.selected.accountId)?.label ?? (ru ? 'Текущий вход CLI' : 'Current CLI login')} · {result.selected.model ?? (ru ? 'Модель по умолчанию' : 'Default model')} · {result.selected.hostId === 'local' ? (ru ? 'Этот компьютер' : 'This computer') : settings.remoteHosts.find(h => h.id === result.selected.hostId)?.label ?? result.selected.hostId} · {result.selected.transport.toUpperCase()}</p><p>{result.dataClass} · {result.contextBytes} {ru ? 'байт контекста' : 'context bytes'} · {result.engine === 'rules' ? (ru ? 'Локальные правила' : 'Local rules') : `Jev · ${result.evaluatorModel}`}</p>
    <p>{result.selected.effort ? effortLabel(settings.locale, result.selected.effort) : (ru ? 'Степень рассуждений по умолчанию CLI' : 'CLI default reasoning effort')} · {ru ? 'цена' : 'cost'} {routeEconomics(result.selected).cost ?? '?'}/5 · {ru ? 'качество' : 'quality'} {routeEconomics(result.selected).quality ?? '?'}/5{result.automatic ? (ru ? ' · собрано автоматически' : ' · assembled automatically') : ''} · {ru ? `проверено связок: ${result.candidateCount}` : `routes checked: ${result.candidateCount}`}{result.engine === 'jev' && result.confidence !== null ? ` · Jev ${Math.round(result.confidence * 100)}%` : ''}</p>
    {result.fallbackReason && <p>{reasons[result.fallbackReason]?.[ru ? 0 : 1] ?? result.fallbackReason} · {ru ? 'использован порядок правил' : 'rule fallback used'}</p>}
    {!acknowledged && <p>{ru ? 'Для этого агента сначала подтвердите риск профиля YOLO. Затем запросите новую рекомендацию.' : 'Acknowledge this agent’s YOLO profile first, then request a fresh recommendation.'}<button type="button" className="agent-settings-button" disabled={busy} onClick={() => void onAcknowledge(result.selected.provider)}>{ru ? 'Подтвердить YOLO' : 'Acknowledge YOLO'}</button></p>}
    <div className="agent-settings-actions"><button type="button" className="agent-settings-button" disabled={disabled || busy || !acknowledged || applied} onClick={() => setApplied(true)}>{applied ? (ru ? 'Рекомендация применена' : 'Recommendation applied') : (ru ? 'Применить рекомендацию' : 'Apply recommendation')}</button><button type="button" className="agent-settings-button" disabled={disabled || busy || !applied || !acknowledged} onClick={() => void launch()}>{ru ? `Запустить ${PROVIDERS[result.selected.provider].label}` : `Launch ${PROVIDERS[result.selected.provider].label}`}</button></div>
   </div>}
  </> : <p>{ru ? 'Маршрутизация выключена. Настройте допустимых исполнителей и включите правила.' : 'Routing is off. Configure allowed routes and enable rules.'}</p>}
  {error && <p className="agent-settings-error" role="alert">{error}</p>}
  <div className="agent-settings-actions"><button type="button" className="agent-settings-button" disabled={busy} onClick={() => onOpenSettings({ section: 'decisions' })}>{ru ? 'Настроить выбор агента' : 'Configure routing'}</button><button type="button" className="agent-settings-button" disabled={busy} onClick={() => onOpenSettings({ section: 'connections', view: 'accounts' })}>{ru ? 'Настроить аккаунты' : 'Configure accounts'}</button></div>
 </details>;
}
